import type { Task, Member, ChatMessage, WorkflowNodeData } from './types'
import type { Node, Edge } from '@xyflow/react'

export const SEED_TASKS: Task[] = [
  {
    id: 'task-1',
    title: 'Design landing page mockups',
    description: 'Create high-fidelity mockups for the new landing page including mobile and desktop views.',
    status: 'done',
    priority: 'high',
    assignee: 'Alice Chen',
    order: 0,
    createdAt: '2026-03-01T10:00:00Z',
    dueDate: '2026-03-10',
    tags: ['design', 'feature'],
    estimatedHours: 16,
  },
  {
    id: 'task-2',
    title: 'Implement authentication flow',
    description: 'Build login, registration, and password reset flows using OAuth2 and JWT tokens.',
    status: 'in-progress',
    priority: 'high',
    assignee: 'Bob Kim',
    order: 0,
    createdAt: '2026-03-05T09:00:00Z',
    dueDate: '2026-03-20',
    tags: ['feature', 'urgent'],
    estimatedHours: 24,
  },
  {
    id: 'task-3',
    title: 'Set up CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing, linting, and deployment to staging.',
    status: 'in-review',
    priority: 'medium',
    assignee: 'Charlie Park',
    order: 0,
    createdAt: '2026-03-08T14:00:00Z',
    dueDate: '2026-03-25',
    tags: ['enhancement'],
    estimatedHours: 8,
  },
  {
    id: 'task-4',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with request/response examples using OpenAPI spec.',
    status: 'todo',
    priority: 'medium',
    assignee: 'Diana Lee',
    order: 0,
    createdAt: '2026-03-10T11:00:00Z',
    dueDate: '2026-03-30',
    tags: ['documentation'],
    estimatedHours: 12,
  },
  {
    id: 'task-5',
    title: 'Database schema optimization',
    description: 'Review and optimize database queries, add missing indexes for performance improvement.',
    status: 'todo',
    priority: 'low',
    assignee: 'Bob Kim',
    order: 1,
    createdAt: '2026-03-12T16:00:00Z',
  },
  {
    id: 'task-6',
    title: 'User acceptance testing',
    description: 'Coordinate UAT sessions with stakeholders and gather feedback for the beta release.',
    status: 'todo',
    priority: 'high',
    assignee: 'Eve Wang',
    order: 2,
    createdAt: '2026-03-14T08:00:00Z',
  },
  {
    id: 'task-7',
    title: 'Mobile responsive fixes',
    description: 'Fix layout issues on tablet and mobile viewports for the dashboard pages.',
    status: 'in-progress',
    priority: 'medium',
    assignee: 'Alice Chen',
    order: 1,
    createdAt: '2026-03-15T10:00:00Z',
  },
  {
    id: 'task-8',
    title: 'Performance audit',
    description: 'Run Lighthouse audits and fix critical performance bottlenecks to achieve 90+ score.',
    status: 'in-review',
    priority: 'low',
    assignee: 'Frank Zhang',
    order: 1,
    createdAt: '2026-03-16T13:00:00Z',
  },
]

/** Generate initials-based avatar placeholder string from a name */
export function getAvatarInitials(name: string): string {
  return name
    .split(' ')
    .map((part) => part[0])
    .join('')
    .toUpperCase()
    .slice(0, 2)
}

const RAW_MEMBERS: Member[] = [
  {
    id: 'member-1',
    name: 'Alice Chen',
    email: 'alice@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2025-06-15',
    avatar: 'AC',
  },
  {
    id: 'member-2',
    name: 'Bob Kim',
    email: 'bob@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-07-01',
    avatar: 'BK',
  },
  {
    id: 'member-3',
    name: 'Charlie Park',
    email: 'charlie@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-08-20',
    avatar: 'CP',
  },
  {
    id: 'member-4',
    name: 'Diana Lee',
    email: 'diana@example.com',
    role: 'qa',
    status: 'active',
    joinedAt: '2025-09-10',
    avatar: 'DL',
  },
  {
    id: 'member-5',
    name: 'Eve Wang',
    email: 'eve@example.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-05-01',
    avatar: 'EW',
  },
  {
    id: 'member-6',
    name: 'Frank Zhang',
    email: 'frank@example.com',
    role: 'developer',
    status: 'inactive',
    joinedAt: '2025-10-15',
    avatar: 'FZ',
  },
  {
    id: 'member-7',
    name: 'Grace Liu',
    email: 'grace@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2025-11-01',
    avatar: 'GL',
  },
  {
    id: 'member-8',
    name: 'Henry Wu',
    email: 'henry@example.com',
    role: 'qa',
    status: 'inactive',
    joinedAt: '2025-12-01',
    avatar: 'HW',
  },
  {
    id: 'member-9',
    name: 'Iris Tanaka',
    email: 'iris@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-07-20',
    avatar: 'IT',
  },
  {
    id: 'member-10',
    name: 'Jack Morrison',
    email: 'jack@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-08-05',
    avatar: 'JM',
  },
  {
    id: 'member-11',
    name: 'Karen Singh',
    email: 'karen@example.com',
    role: 'qa',
    status: 'active',
    joinedAt: '2025-09-25',
    avatar: 'KS',
  },
  {
    id: 'member-12',
    name: 'Leo Martinez',
    email: 'leo@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2025-10-01',
    avatar: 'LM',
  },
  {
    id: 'member-13',
    name: 'Mia Johnson',
    email: 'mia@example.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-04-15',
    avatar: 'MJ',
  },
  {
    id: 'member-14',
    name: 'Nathan Patel',
    email: 'nathan@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-11-10',
    avatar: 'NP',
  },
  {
    id: 'member-15',
    name: 'Olivia Brown',
    email: 'olivia@example.com',
    role: 'qa',
    status: 'inactive',
    joinedAt: '2025-06-01',
    avatar: 'OB',
  },
  {
    id: 'member-16',
    name: 'Peter Nguyen',
    email: 'peter@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2025-12-15',
    avatar: 'PN',
  },
  {
    id: 'member-17',
    name: 'Quinn Riley',
    email: 'quinn@example.com',
    role: 'designer',
    status: 'active',
    joinedAt: '2026-01-05',
    avatar: 'QR',
  },
  {
    id: 'member-18',
    name: 'Rachel Torres',
    email: 'rachel@example.com',
    role: 'developer',
    status: 'inactive',
    joinedAt: '2025-08-15',
    avatar: 'RT',
  },
  {
    id: 'member-19',
    name: 'Sam O\'Brien',
    email: 'sam@example.com',
    role: 'qa',
    status: 'active',
    joinedAt: '2026-01-20',
    avatar: 'SO',
  },
  {
    id: 'member-20',
    name: 'Tina Yamamoto',
    email: 'tina@example.com',
    role: 'admin',
    status: 'active',
    joinedAt: '2025-05-20',
    avatar: 'TY',
  },
  {
    id: 'member-21',
    name: 'Uma Krishnan',
    email: 'uma@example.com',
    role: 'developer',
    status: 'active',
    joinedAt: '2026-02-01',
    avatar: 'UK',
  },
  {
    id: 'member-22',
    name: 'Victor Sousa',
    email: 'victor@example.com',
    role: 'designer',
    status: 'inactive',
    joinedAt: '2025-09-05',
    avatar: 'VS',
  },
]

/** Per-member skills + department, merged into SEED_MEMBERS below. Lets workflows
 *  target "a developer skilled in X" / "someone in the Security dept". */
const MEMBER_EXTRAS: Record<string, { skills: string[]; department: string }> = {
  'member-1': { skills: ['UI Design', 'Figma'], department: 'Design' },
  'member-2': { skills: ['React', 'TypeScript', 'Node.js'], department: 'Frontend' },
  'member-3': { skills: ['CI/CD', 'Docker', 'Kubernetes'], department: 'Platform' },
  'member-4': { skills: ['Test Automation', 'Cypress'], department: 'QA' },
  'member-5': { skills: ['Project Management'], department: 'Operations' },
  'member-6': { skills: ['Java', 'Spring'], department: 'Backend' },
  'member-7': { skills: ['UX Research', 'Prototyping'], department: 'Design' },
  'member-8': { skills: ['Manual QA'], department: 'QA' },
  'member-9': { skills: ['Python', 'Machine Learning', 'Data'], department: 'Data' },
  'member-10': { skills: ['Go', 'Backend', 'gRPC'], department: 'Backend' },
  'member-11': { skills: ['Performance Testing', 'k6'], department: 'QA' },
  'member-12': { skills: ['Branding', 'Illustration'], department: 'Design' },
  'member-13': { skills: ['People Ops'], department: 'Operations' },
  'member-14': { skills: ['React', 'Next.js', 'GraphQL'], department: 'Frontend' },
  'member-15': { skills: ['Regression'], department: 'QA' },
  'member-16': { skills: ['Security', 'Auth', 'OAuth'], department: 'Security' },
  'member-17': { skills: ['Design Systems', 'Figma'], department: 'Design' },
  'member-18': { skills: ['PHP', 'Laravel'], department: 'Legacy' },
  'member-19': { skills: ['API Testing', 'Postman'], department: 'QA' },
  'member-20': { skills: ['Finance'], department: 'Operations' },
  'member-21': { skills: ['Rust', 'Performance', 'WASM'], department: 'Backend' },
  'member-22': { skills: ['Motion', '3D'], department: 'Design' },
}

export const SEED_MEMBERS: Member[] = RAW_MEMBERS.map((member) => ({
  ...member,
  ...(MEMBER_EXTRAS[member.id] ?? {}),
}))

/** Seed direct-message conversations, keyed by memberId. */
export const SEED_MESSAGES: Record<string, ChatMessage[]> = {
  'member-2': [
    { id: 'msg-seed-1', memberId: 'member-2', from: 'them', body: '인증 플로우 작업 진행 중입니다. 리뷰 필요하면 말씀해 주세요.', timestamp: 1773532800000 },
    { id: 'msg-seed-2', memberId: 'member-2', from: 'me', body: '확인했어요, 고생 많으십니다!', timestamp: 1773533400000 },
  ],
  'member-3': [
    { id: 'msg-seed-3', memberId: 'member-3', from: 'them', body: 'CI/CD 파이프라인 스테이징 배포까지 설정해 뒀어요.', timestamp: 1773619200000 },
  ],
}

export const SEED_WORKFLOW_NODES: Node<WorkflowNodeData>[] = [
  // Stage nodes — 메인 워크플로우
  {
    id: 'planning',
    type: 'stage',
    position: { x: 0, y: 0 },
    data: { label: '기획', description: '요구사항 분석 및 기획' },
  },
  {
    id: 'design',
    type: 'stage',
    position: { x: 260, y: 0 },
    data: { label: '디자인', description: 'UI/UX 디자인' },
  },
  {
    id: 'dev',
    type: 'stage',
    position: { x: 520, y: 0 },
    data: { label: '개발', description: '기능 구현' },
  },
  {
    id: 'review',
    type: 'stage',
    position: { x: 780, y: 0 },
    data: { label: '코드 리뷰', description: 'PR 리뷰 및 피드백' },
  },
  {
    id: 'qa',
    type: 'stage',
    position: { x: 1040, y: 0 },
    data: { label: 'QA 테스트', description: '품질 검증' },
  },
  {
    id: 'deploy',
    type: 'stage',
    position: { x: 1300, y: 0 },
    data: { label: '배포', description: '프로덕션 배포' },
  },
  // Task nodes
  {
    id: 'labeling',
    type: 'task',
    position: { x: 520, y: 220 },
    data: { label: '라벨링', description: '데이터 라벨링 작업' },
  },
  {
    id: 'monitoring',
    type: 'task',
    position: { x: 1040, y: 220 },
    data: { label: '모니터링', description: '서비스 모니터링 설정' },
  },
]

export const SEED_WORKFLOW_EDGES: Edge[] = [
  // 메인 플로우
  { id: 'e-planning-design', source: 'planning', target: 'design' },
  { id: 'e-design-dev', source: 'design', target: 'dev' },
  { id: 'e-dev-review', source: 'dev', target: 'review' },
  { id: 'e-review-qa', source: 'review', target: 'qa' },
  { id: 'e-qa-deploy', source: 'qa', target: 'deploy' },
  // 분기
  { id: 'e-dev-labeling', source: 'dev', target: 'labeling', style: { strokeDasharray: '5 5' } },
  { id: 'e-qa-monitoring', source: 'qa', target: 'monitoring', style: { strokeDasharray: '5 5' } },
]
